name: Builds the Homie
on:
  push:

jobs:
  build:
    name: Matrix ${{matrix.name}}
    strategy:
      matrix:
        include:
          - name: linux_x64
            os: ubuntu-latest
          - name: linux_arm64
            os: ubuntu-24.04-arm
          - name: win64
            os: windows-latest
            suff: .exe
            build_path: Release/
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.name }}
      uses: nicledomaS/cmake_build_action@v1.4

    - name: Rename artifacts
      run: |
        mkdir artifacts
        mv build/${{matrix.build_path}}Homie${{matrix.suff}} artifacts/Homie_${{ matrix.name }}${{matrix.suff}}

    - name: Archive Homie_${{ matrix.name }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie_${{ matrix.name }}${{matrix.suff}}
        path: artifacts

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    name: Tag & Release
    steps:
      - uses: actions/checkout@v4
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: archive
          pattern: Homie*
          delete-merged: false
      - name: Tagging version of release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN}}
          TAG_PREFIX: v
      # - name: Create Release
        # uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/v')
