name: Builds the Homie
on:
  push:

jobs:
  build:
    name: Matrix ${{matrix.var}}
    strategy:
      matrix:
        var: [1,2,3,4]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Matrix test
      run: echo "Hello from matrix number:${{ matrix.var }}"

    - name: Set up C++ CMake
      run: sudo apt-get install -y gcc cmake

    - name: Build
      run: cmake . && make

    - name: Run
      run: ./Homie

    - name: Rename artifacts
      run: |
        mkdir artifacts
        mv Homie "artifacts/Homie${{ matrix.var }}"

    - name: Archive Homie${{ matrix.var }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie${{ matrix.var }}
        path: artifacts

  merge:
    runs-on: ubuntu-latest
    needs: build
    name: Merge Output Artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: archive
          pattern: Homie*
          delete-merged: true
