name: Builds the Homie
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up C++ CMake
      run: sudo apt-get install -y gcc cmake

    - name: Build
      run: cmake . && make

    - name: Run
      run: ./Homie
