name: Builds the Homie
on:
  push:

jobs:
  build:
    name: Matrix ${{matrix.var}}
    strategy:
      matrix:
        name: linux_x64
          os: ubuntu-latest
        name: linux_arm64
          os: ubuntu-24.04-arm
        name: win64
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.name }}
      uses: nicledomaS/cmake_build_action@v1.4

    - name: Rename artifacts
      run: |
        mkdir artifacts
        if [ ${{ matrix.name }} -eq "win64" ]
          mv Homie.exe "artifacts/Homie_${{ matrix.name }}.exe"
        mv Homie "artifacts/Homie_${{ matrix.name }}"

    - name: Archive Homie${{ matrix.var }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie_${{ matrix.name }}*
        path: artifacts

  merge:
    runs-on: ubuntu-latest
    needs: build
    name: Merge Output Artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: archive
          pattern: Homie*
          #delete-merged: true
