name: Builds the Homie
on:
  push:

env:
  test_env1: ""
  test_env2: ""

jobs:
  build:
    name: Matrix ${{matrix.name}}
    strategy:
      matrix:
        include:
          - name: linux_x64
            os: ubuntu-latest
          - name: linux_arm64
            os: ubuntu-24.04-arm
          - name: win64
            os: windows-latest
            suff: .exe
            build_path: Release/
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.name }}
      uses: nicledomaS/cmake_build_action@v1.4

    - name: Rename artifacts
      run: |
        mkdir artifacts
        mv build/${{matrix.build_path}}Homie${{matrix.suff}} artifacts/Homie_${{ matrix.name }}${{matrix.suff}}

    - name: Archive Homie_${{ matrix.name }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie_${{ matrix.name }}${{matrix.suff}}
        path: artifacts

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    name: Tag
    outputs:
      pretag: ${{ steps.previous_tag.outputs.tag }}
      postag: ${{ steps.post_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: archive
          pattern: Homie*
          delete-merged: false
      - id: previous_tag
        name: Save previous latest tag
        run: |
          echo "tag=$(git tag | tail -n 1)" >> "$GITHUB_OUTPUT"
          test_env1=$(git tag | tail -n 1)
          echo "test_env1=$test_env1"
      - name: Tagging version of release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: none
      - id: post_tag
        name: Save post latest tag
        run: |
          echo "tag=$(git tag | tail -n 1)" >> "$GITHUB_OUTPUT"
          test_env2=$(git tag | tail -n 1)
          echo "test_env1=$test_env1"
          echo "test_env2=$test_env2"
  release:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    needs: deploy
    name: Release
    steps:
      - name: Compare tags
        env:
          PRETAG: ${{ needs.deploy.outputs.pretag }}
          POSTAG: ${{ needs.deploy.outputs.postag }}
        run: |
          if [[ "$PRETAG" == "$POSTAG" ]]; then
            echo "Tag isn't updated"
          else
            echo "Tag is updated"
          fi
          echo "pretag=$PRETAG postag=$POSTAG"
          git tag | tail -n 2
          echo "test_env1=$test_env1"
          echo "test_env2=$test_env2"
      - name: Create Release
#        uses: softprops/action-gh-release@v2
        if: ${{ ! needs.deploy.outputs.pretag == needs.deploy.outputs.postag }}
        run: echo "Release creation..."
