name: Builds the Homie
on:
  push:

jobs:
  build:
    name: Matrix ${{matrix.name}}
    strategy:
      matrix:
        include:
          - name: linux_x64
            os: ubuntu-latest
          - name: linux_arm64
            os: ubuntu-24.04-arm
          - name: win64
            os: windows-latest
            suff: .exe
            build_path: Release/
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.name }}
      uses: nicledomaS/cmake_build_action@v1.4

    - name: Rename artifacts
      run: |
        mkdir artifacts
        mv build/${{matrix.build_path}}Homie${{matrix.suff}} artifacts/Homie_${{ matrix.name }}${{matrix.suff}}

    - name: Archive Homie_${{ matrix.name }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie_${{ matrix.name }}${{matrix.suff}}
        path: artifacts

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    name: Tag
    outputs:
      pretag: ${{ steps.previous_tag.outputs.tag }}
      postag: ${{ steps.post_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - id: previous_tag
        name: Save previous latest tag
        run: echo "tag=$(git tag --sort=-v:refname | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Tagging version of release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: none

      - id: post_tag
        name: Save post latest tag
        run: echo "tag=$(git tag --sort=-v:refname | head -n 1)" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: deploy
    name: Release
    permissions:
      contents: write
    env:
      PRETAG: ${{ needs.deploy.outputs.pretag }}
      POSTAG: ${{ needs.deploy.outputs.postag }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true

      - name: Generate Changelog
        run: |
          echo "## Changelog" > CHANGELOG.md
          git log -$(git rev-list --count $PRETAG..$POSTAG) --pretty=format:"- [%B](commit/%h)"  >> CHANGELOG.md

      - name: Create Release
        if: env.PRETAG != env.POSTAG
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.POSTAG }}
          files: artifact/*
          body_path: CHANGELOG.md
