name: Builds the Homie
on:
  push:

jobs:
  build:
    name: Matrix ${{matrix.name}}
    strategy:
      matrix:
        include:
          - name: linux_x64
            os: ubuntu-latest
          - name: linux_arm64
            os: ubuntu-24.04-arm
          - name: win64
            os: windows-latest
            suff: .exe
            build_path: Release/
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.name }}
      uses: nicledomaS/cmake_build_action@v1.4

    - name: Rename artifacts
      run: |
        mkdir artifacts
        mv build/${{matrix.build_path}}Homie${{matrix.suff}} artifacts/Homie_${{ matrix.name }}${{matrix.suff}}

    - name: Archive Homie_${{ matrix.name }}
      uses: actions/upload-artifact@v4
      with:
        name: Homie_${{ matrix.name }}${{matrix.suff}}
        path: artifacts

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    name: Tag & Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: archive
          pattern: Homie*
          delete-merged: false
      - name: Save previous latest tag
        id: save_previous_tag
        run: |
          pretag=$(git tag | tail -n 1)
          echo "::set-output name=pretag::$pretag"
      - name: Tagging version of release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
      - name: Save latest tag
        id: save_latest_tag
        run: |
          postag=$(git tag | tail -n 1)
          echo "::set-output name=postag::$postag"
      - name: Compare tags
        run: |
          pretag=${{ steps.save_previous_tag.outputs.pretag }}
          postag=${{ steps.save_latest_tag.outputs.postag }}
          if [[ "$pretag" == "$postag" ]]; then
            echo "Tag isn't updated"
          else
            echo "Tag is updated"
          fi
          echo "pretag=$pretag postag=$postag"
          git tag | tail -n 2
      # - name: Create Release
        # uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/v')
